### ISSUE TITLE
Integrate Linter

### ISSUE THREAD

**Issue by k0zlov** [k0zlov/chat-app#4]
To ensure code quality and consistency across the Flutter messaging application project, integrate the very_good_analysis package for linting. This task involves adding the package to the project, configuring it, and resolving any initial linting errors or warnings that arise. Following these steps will help maintain a high standard for the project's codebase.

**Comment by k0zlov** [comment]
Forgot to open an issue before commiting.
Link to commit -> c2d889acbcae06940b1489d349c68e9b895fce1b

**Comment by starchykov** [comment]
Please add the following lint ruses:

    lines_longer_than_80_chars: false

    omit_local_variable_types: false

    use_key_in_widget_constructors: true

    always_use_package_imports: true

    prefer_const_constructors: true

    prefer_const_declarations: true

    prefer_single_quotes: true

    avoid_init_to_null: true

    #   Sort constructor declarations before other members.
    sort_constructors_first: true

    #   Sort child properties last in widget instance creations.
    sort_child_properties_last: true

    #   DO use Flutter TO DO format. // TO DO(username): message, https://URL-to-issue.
    flutter_style_todos: true

    #   DO follow the directive ordering conventions in Effective Dart:
    directives_ordering: true

**Comment by starchykov** [comment]
Implemented.
